from selenium.webdriver.common.by import By

class Register_locators:
    name_input = (By.XPATH, "//input[@aria-label='Name']")
    surname_input = (By.XPATH, "//input[@aria-label='Last name']")
    email_input = (By.XPATH,"//input[@aria-label='Email']")
    password_input = (By.XPATH,"//input[@aria-label='Password']")
    confirm_pass_inp = (By.XPATH,"//input[@aria-label='Password confirmation']")
    next_button = (By.XPATH, "//button[@class='q-btn q-btn-item non-selectable no-outline q-btn--standard q-btn--rectangle bg-primary text-white q-btn--actionable q-focusable q-hoverable q-btn--no-uppercase q-ml-auto']")

    who_am_i = (By.XPATH,"//span[normalize-space()='Fan']")
    role_picker_fun = (By.XPATH, "//div[contains(@class,'q-item__label')]//span[contains(text(),'Fan')]")
    role_picker_player = (By.XPATH, "//div[contains(@class,'q-item__label')]//span[contains(text(),'Player')]")
    username_input = (By.XPATH, "//input[contains(@aria-label,'Username')]")
    phone_input = (By.XPATH, "//input[@aria-label='Phone']")
    next_fan_finish = (By.CSS_SELECTOR, ".q-btn.q-btn-item.non-selectable.no-outline.q-btn--standard.q-btn--rectangle.bg-primary.text-white.q-btn--actionable.q-focusable.q-hoverable.q-btn--no-uppercase")

    gender_picker = (By.XPATH, "//div[@aria-label='Gender']")
    gender_male = (By.XPATH, "//div[@class='q-item__label'])[1]")
    birth_date_picker = (By.XPATH,"//input[@aria-label='Birth Date']")
    date_range_max = (By.XPATH,"//span[contains(text(),'2022')]")
    date_range_min = (By.XPATH,"//span[contains(text(),'2015')]")
    date_range_confirm = (By.XPATH,"//span[@class='block'][normalize-space()='1']")
    date_picker_close = (By.XPATH, "//span[contains(text(),'Close')]")
    preferred_position = (By.XPATH, "//div[@aria-label='Preferred position']")
    secondary_position = (By.XPATH, "//div[@aria-label='Secondary position']")
    units_measurement = (By.XPATH, "//div[@aria-label='Units of measurement']")
    measure = (By.XPATH, "//span[normalize-space()='Imperial']")
    height = (By.XPATH, "//input[@aria-label='Height']")
    weight = (By.XPATH, "//input[@aria-label='Weight']")
    education = (By.XPATH, "//div[@aria-label='Type of educational institution']")
    education_type = (By.XPATH, "//span[normalize-space()='High School']")
    current_school = (By.XPATH, "//input[@aria-label='Current school / university']")
    preferred_foot = (By.XPATH, "//div[@aria-label='Preferred foot']")
    foot = (By.XPATH, "//div[@aria-label='Preferred foot']")
    current_club = (By.XPATH, "//input[@aria-label='Current club']")
    agent = (By.XPATH, "//input[@aria-label='Agent']")
    nationality_picker = (By.XPATH, "//input[@aria-label='Nationality']")
    nationality = (By.XPATH, "(//div[@class='q-item__label'])[9]")
    province = (By.XPATH, "//input[@aria-label='Province']")
    address_line = (By.XPATH, "//input[@aria-label='Address line']")
    zip_code = (By.XPATH, "//input[@aria-label='Zip code']")
    player_register_finish = (By.XPATH, "//span[contains(text(),'Next')]")