# This workflow will install Python dependencies, run tests and lint with a single version of Python.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: vvp_players
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: read

env:
  BASE_URL: ${{ secrets.BASE_URL }}
  APP_PATH : ${{ secrets.APP_PATH }}
  MEDIA_PATH : ${{ secrets.MEDIA_PATH }}
  
  BASE_URL_REGISTER : ${{ secrets.BASE_URL_REGISTER }}
  BASE_URL_LOGIN : ${{ secrets.BASE_URL_LOGIN }}

  LOGIN_FAN : ${{ secrets.LOGIN_FAN }}
  FAN : ${{ secrets.FAN }}
  LOGIN_PLAYER : ${{ secrets.LOGIN_PLAYER }}
  PLAYER : ${{ secrets.PLAYER }}
  USERNAME_PLAYER : ${{ secrets.USERNAME_PLAYER }}
  PLAYER_USERNAME : ${{ secrets.PLAYER_USERNAME }}
  LOGIN_ADMIN : ${{ secrets.LOGIN_ADMIN }}
  LOGIN_MODERATOR : ${{ secrets.LOGIN_MODERATOR }}
  PASSWORD_ADMIN : ${{ secrets.PASSWORD_ADMIN }}

  PASSWORD : ${{ secrets.PASSWORD }}
jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F7 --show-source --statistics --disable-noqa
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    - name: Test with pytest
      run: |
        pytest
